-- 1. Create the entries table
create table entries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  reward text,
  fee bigint,
  type text,
  reward_id text,
  code text,
  ip_address text,
  timestamp timestamptz default now()
);

-- 2. Enable Row Level Security (RLS) recommended for security
alter table entries enable row level security;

-- 3. Create a policy to allow ANYONE (anon) to INSERT their entry
create policy "Allow public inserts"
on entries for insert
to anon
with check (true);

-- 4. Create a policy to allow ADMINS (or public for now) to VIEW entries
-- For simplicity in this static site without auth, we'll allow public read
-- In a real app, you'd restrict this to authenticated users only
create policy "Allow public read"
on entries for select
to anon
using (true);
